language: node_js
node_js:
    - "0.12"
    - "0.11"

before_install:
    - npm install -g mocha

script:
    - npm run cover

after_install:
    - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
