sudo: false
language: node_js

node_js:
    - "4.6.0"
    - "4.5.0"
    - "0.12"
    - "0.11"

env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

before_install:
    - npm install -g mocha

script:
    - npm run cover

# Send coverage data to Coveralls
after_script:
    - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
